### PR TITLE
feat: add export plan

### PR DESCRIPTION
**Pull request by pepperoni505**
This proposal adds the boilerplate code needed to add batch exporting.

### CODE REVIEW

**Comment by julienduroure** [comment]
Hello,
Seems this solution is better than the previous one.
But loop on objects is only done on "root objects", so I don't know how you are managing plan where objects have parents?
Same for animated objects

Not that a big refactoring of export will come in next months, where tree is first store in a virtual vtree, and then exported. 

(See #1494 for what it will be)
I will also add some hook to be able to change the vtree filtering.

**Comment by pepperoni505** [comment]
I'll fix that. What should I do in a situation where a root object has a grandchild, but the parent of that object isn't exported?

e.g.
- Object 1 (export)
    - Object 2 (don't export)
        - Object 3 (export)

**Comment by julienduroure** [comment]
In current master, object 2 is exported as empty. 

In future vtree version, object 3 is reparented to object 1, and object 2 is not exported

**Comment by pepperoni505** [comment]
So in this instance, would it be best to just wait until the vtree PR gets merged ?

**Comment by pepperoni505** [comment]
Closing this to wait for the vtree PR.

**Pull request closed without merging**
