### PR TITLE
Import: use Eevee Specular node for pbrSpecGloss materials

### PR DESCRIPTION
**Pull request by scurest**
Since <2.80 support was dropped, use option 3 from #303 (a Eevee Specular node) for spec/gloss materials.

A MixShader + Transparent node is still used for alpha.

spegl-after

### CODE REVIEW

**Comment by julienduroure** [comment]
What about Cycles? This node is only for Eevee
One (heavy) solution is to have different node setup for Eevee and Cycles, using material output dropdown list

image

**Comment by scurest** [comment]
It just switches the scene to Eevee (see the first few lines in `pbr_specular_glossiness`). Is that okay?

**Comment by julienduroure** [comment]
What I mean is that currently all node trees we created are compatible in both Eevee and Cycles.
This node tree is only compatible with Eevee. Even if you switch to Eevee in code, if user want to use this asset in Cycles, he can't.
I think we need to keep compatibility in both render engine as much as possible. Of course, in this case, the node is only for Eevee, but I think we need to have a minimal fallback for Cycles

**Comment by scurest** [comment]
Okay, that makes sense. Since like you said, adding a separate track of nodes for different Material Outputs would make the graph heavier rather than lighter, I'll just leave this as option 1.

**Pull request closed without merging**
