### PR TITLE
Export vtree

### PR DESCRIPTION
**Pull request by julienduroure**

### CODE REVIEW

**Comment by julienduroure** [comment]
Still a WIP.
This is only a first step: Have a virtual Tree for nodes, and then use this tree to construct glTF tree.

Still have some TODO to manage, because managing skin & joints with this current system is not easy

**Comment by julienduroure** [comment]
Seems tests are KO only for pull_request because a cache issue (still caching 2.93 where push caches 3.0)
Anyone know how to solve it?

**Comment by julienduroure** [comment]
2 different new things in this branch:
- manage a tree before export. It uses an uuid for each "real" object, and these uuid are passed to other function (and can be used for caching)
- Using custom caching, as proposed by scurest. Already used in some cases here.

In current version:
- All tested collection instance issues are solved
- No more proxy check is needed (for example Text and Mesh using same name in different linked data are now ok)

In attachment a test case for multi level collection instance, for materials, and meshes

[collections.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/6735246/collections.zip)
[materials.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/6735248/materials.zip)
[mesh.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/6735249/mesh.zip)


Of course lots of work are still needed, but this is a first step.

**Comment by dysbulic** [comment]
¿Will the resolution of this issue fix the fact that the current glTF export flattens all of Blender's collections into a single level?

For example, this .blend scene graph:

Screenshot from 2021-08-09 15-10-08

Becomes this single-tiered structure after a round-trip through the glb export/import process:

Screenshot from 2021-08-09 15-12-09

If this issue fixes that problem, I would like to put a little ETH on it through [Gitcoin](//gitcoin.co/funding/new). The scene graph is so handy for describing nested relationships, and I really wish we could get access to it when rendering glTF files.

**Comment by dysbulic** [comment]
About two weeks ago I posted a question as to whether this code would allow exporting a hierarchical scene collection.

I just wanted to poke again and see if I could get an answer. I looked at the code changes, and I see there's a tree structure being saved. That's promising…

I created a [sample glTF file](https://github.com/dysbulic/stay/blob/react/public/cubes.gltf) that contains nested children. It produces a scene hierarchy like:

Screenshot from 2021-08-24 12-45-30

So, all the nesting is of objects rather than collections. In the [glTF spec](https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#:~:text=%20any%20gltf%20object%20can%20have%20an%20optional%20extensions%20property), it says `extensions` are allowed on any glTF object, is it possible to set an extension property that causes the group to open as a collection?

**Comment by julienduroure** [comment]
I open a new issue #1456 to discuss about that.
This PR is a technical refactoring. I don't want to mix with feature requests

**Comment by julienduroure** [comment]
Ok, seems it's now time to deeply test this PR.
Don't hesitate to test, and report any regression.
I will prepare a document next week to explain what are the changes, why we can have some performance decrease in some cases (but for more accuracy in export). I will share this on most know Blender user forum/site, to have a wide test range.

**Comment by julienduroure** [comment]
Here are more information about how people can test it: https://devtalk.blender.org/t/test-future-gltf-exporter-version/22657

**Comment by emackey** [comment]
@julienduroure I tried exporting a model with multiple same-name NLA tracks, using a [vtree build](https://builder.blender.org/download/experimental/gltf_vtree/) from today.  It looks like all my parts came out animated separately.  I have "Group by NLA track" checked, but it didn't perform any grouping, they all came out as loose pieces.

**Comment by julienduroure** [comment]
@emackey Do you have your .blend test case? 
I can't reproduce here for now on simple test case

image

image

**Comment by emackey** [comment]
Took a while to figure out how to reproduce, but it turns out the bug activates when "Include Selected Objects" is checked in the exporter options.  The combined NLA track exports alongside loose animations per-object.

[NLA_Test_vtree.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/8050223/NLA_Test_vtree.zip)

In the above example, there should be only one NLA animation exported, called "CubeDance."  But when "Include Selected Objects" is used, the combined animation appears alongside individual cube animations.

**Comment by julienduroure** [comment]
@emackey Nice catch!
I just pushed a fix, and ask builder to compile a new build. Should be available in a few hours

**Comment by julienduroure** [comment]
@s-light You need at least 3.1 to run this branch, you can't use 3.0

**Comment by emackey** [comment]
@s-light This branch has its own build, too:  https://builder.blender.org/download/experimental/gltf_vtree/

**Comment by s-light** [comment]
sorry... is not related to vtree.
it also happens in the current master - 
and after some digging i found that the used `use_frame_range` is a blender3.1 feature....

**Comment by Capital-Asterisk** [comment]
Hi, I just tried out these changes to fix my problems in #1576. I've noticed that skins are duplicated if multiple objects are parented to a single armature:
```json
"skins" : [
    {
        "inverseBindMatrices" : 6,
        "joints" : [
            1,
            0
        ],
        "name" : "Armature"
    },
    {
        "inverseBindMatrices" : 6,
        "joints" : [
            1,
            0
        ],
        "name" : "Armature"
    }
],
```
I'm not sure if this is intentional, but this did not happen before. It may re-introduce #566, though this issue and its resolution seems complicated. Unlike the mentioned issue, the inverseBindMatrices are exactly the same in this case.

For some context, I'm writing a C++ application that uses gltf, and relies on nodes within the same armature to have the same skin; it would abort otherwise.

**Comment by julienduroure** [comment]
> I've noticed that skins are duplicated if multiple objects are parented to a single armature

Confirmed. I will have a look soon

**Comment by julienduroure** [comment]
@Capital-Asterisk I just Fixed the duplicate skin data bug

**Pull request merged**
