### PR TITLE
Upgrade yarn packages in test folder.

### PR DESCRIPTION
**Pull request by emackey**
@pjoe Are you still following this repo?  😄

### CODE REVIEW

**Comment by pjoe** [comment]
Now and then 👅 Unfortunately my day job doesn't currently give me much extra time for this.

**Comment by pjoe** [comment]
Changes lgtm 👍

**Comment by emackey** [comment]
Thanks, I hope you're doing well!

**Comment by pjoe** [comment]
@emackey likewise. Hiding at home with family 😄

**Pull request merged**
