### PR TITLE
Fixed bezier control points to cubic spline tangents conversion

### PR DESCRIPTION
**Pull request by Andari85**
Related to:
https://github.com/KhronosGroup/glTF-Blender-Exporter/issues/90
https://github.com/KhronosGroup/glTF-Blender-IO/issues/960
https://github.com/KhronosGroup/glTF/issues/1778
https://github.com/KhronosGroup/glTF-Blender-Exporter/commit/42c46350f06e7401b941474c81bae60837a86ade
The commit above does not seem to have made it to this new repository.
Exported animations now maintain derivatives of curves at keyframes.

### CODE REVIEW

**Comment by Andari85** [comment]
Sorry for the force push, I just quickly corrected pushing with wrong credentials.

**Comment by julienduroure** [comment]
Thanks for your PR
I will have a look soon.

**Comment by scurest** [comment]
FWIW, I didn't test it, but this looks correct to me.

I had to check how the comment about "intermediately use a point at t+1 to define the tangent" works: it's clever, instead of the code needing to know how to transform both the ordinate and the derivative

$$
\begin{align}
T &: f(t) \mapsto Af(t) + B \\
T' &: f'(t) \mapsto Af'(t)
\end{align}
$$

by working with f(t)+f'(t), which is the value of (the tangent line to f at t) evaluated at t+1, the code only needs to know how to transform ordinates

$$
\begin{align}
T &: f(t) \mapsto Af(t) + B \\
T &: f(t) + f'(t) \mapsto A(f(t) + f'(t)) + B
\end{align}
$$

because the transformed derivative can be recovered by subtraction $T(f(t)+f'(t)) - T(f(t)) = Af'(t)$.

The comment for in_tangents claims instead to "use a point at t-1 to define the tangent". In this case it would work with f(t)-f'(t) and recover the transformed derivative by reverse subtraction $T(f(t)) - T(f(t)-f'(t)) = Af'(t)$. It's not clear to me which one of these two forms the old code was actually trying to use, but this patch is definitely using the "t+1" form, not the "t-1" form, in both cases (which seems easier anyway).

So @Andari85, the only thing I'd say is update the comment near key.in_tangent to say "use a point at **t+1** to define the tangent" since that's what it does.

**Comment by Andari85** [comment]
Thanks for the note. I added more info to the comment.

**Comment by julienduroure** [comment]
@Andari85 Seems your didn't signed the CLA with the last github user you used to push

**Comment by Andari85** [comment]
Oh no, not again...

**Comment by julienduroure** [comment]
I didn't test it yet, but here is a (maybe) related report: #1436

**Comment by scurest** [comment]
> here is a (maybe) related report: https://github.com/KhronosGroup/glTF-Blender-IO/issues/1436

This fixes it.

**Comment by Andari85** [comment]
Yes, it is described exactly as the issue I had to solve with this.
When may we expect it to be merged?

**Comment by julienduroure** [comment]
> When may we expect it to be merged?

I plan to review/test (but seems OK) and merge next week

**Comment by julienduroure** [comment]
Thanks a lot for your PR!

**Comment by Andari85** [comment]
Thank you for handling it quickly and accepting it!

**Pull request merged**
