### PR TITLE
fix gltf_gather_hook

### PR DESCRIPTION
**Pull request by jjcasmar**
gather_gltf_hook should happen before finalizing scenes, in case it adds content that has to be finalized

### CODE REVIEW

**Comment by julienduroure** [comment]
Not sure why you deleted the `exporter.traverse_extensions()` call.
Seems __gltf.extensions is never traversed elsewhere?

**Comment by jjcasmar** [comment]
Ill have to rechecl how this world, cant remember

**Comment by julienduroure** [comment]
Any news?

**Comment by julienduroure** [comment]
Closing this PR, will be replaced by #1571

**Pull request closed without merging**
