### PR TITLE
Clean up readme.

### PR DESCRIPTION
**Pull request by donmccurdy**
- Update version.
- Updates documentation links, and makes them more prominent.
- Remove references to 2.80 beta.
- Remove comparison to older exporter.

### CODE REVIEW

**Comment by donmccurdy** [comment]
@julienduroure do you think it's worthwhile to include the addon version this way, or is that just more work to update with releases, unnecessarily?

**Comment by emackey** [comment]
Let's keep the addon version out of this README.  There shouldn't be anything here that's tied to minor revisions, and this file stays under Git's control.

**Comment by emackey** [comment]
I think we can remove the whole "Version" heading.

**Comment by donmccurdy** [comment]
Sounds good, done. ✅

**Comment by emackey** [comment]
Thanks @donmccurdy.

**Pull request merged**
