### PR TITLE
Clearcoat unit tests

### PR DESCRIPTION
**Pull request by emackey**
This is a follow-on to #931 that adds unit tests for clearcoat.

Currently the test is failing.  I left a one-line suggestion on #931 that will fix it.  Merge that before merging this.

/cc @donmccurdy

### CODE REVIEW

**Comment by emackey** [comment]
Don submitted a fix to his branch.  So, merging Don's branch in here should change the unit tests from red to green.

**Comment by emackey** [comment]
And they passed!

**Comment by scurest** [comment]
@emackey (Sorry, this is just a question, not related to this PR, and I didn't want to make an issue.) What is the meaning of the numbers prefixed to the test files? How did you pick `08_` for this PR for example?

**Comment by emackey** [comment]
Those numbers have become a little messy I guess.  I picked 08 because I was using that for ORM combinations, and the clearcoat combination is the same sort of thing.  I wanted to reuse the `08_*.png` image test assets.  Probably I should put base + alpha combination in there as well, but I haven't got around to it yet.

I'm open to suggestions for re-org, but unfortunately I can't invest a whole lot of time on the test framework.  I just work on it when I get a few spare few moments.

**Comment by scurest** [comment]
Hmm, well I still don't get it, haha. I didn't want to reorg them. More like, if I wanted to add a test file, how would I know what number I should use?

**Comment by emackey** [comment]
If it's something new, just make a new number, that should be fine.

**Comment by donmccurdy** [comment]
A new number as in `01`? Or the highest existing number + 1? I was a bit confused doing this for https://github.com/KhronosGroup/glTF-Blender-IO/pull/800 as well. 😅

**Comment by emackey** [comment]
Highest number plus 1.

**Comment by scurest** [comment]
Okay. Thanks for answering!

**Pull request merged**
