### PR TITLE
Fix 642

### LINKED ISSUE #642: No tiling on roughness
**Describe the bug**

**To Reproduce**
have made several materials  - all with roughness
but tiling applied to roughness wont be exported!

heres my initial Blen Material Setup 
2019-08-30 21_31_27-Blender

**Expected behavior**
Albedo and Normal are tiled.
In my logic Roughness should also be tiled 10x - but it isnt...
even if i make a separate node for the roughness it wont work

grafik

**Screenshots**

**.blend file/ .gltf**
[roughnesTilingIssue.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/3561272/roughnesTilingIssue.zip)

**Version**
 - OS: doesnt matter...
 - Blender Version 2.80

### PR DESCRIPTION
**Pull request by julienduroure**
Fix #642 + implement texture transform export for occlusion map

@emackey Can you please have a look, materials are not my best known part of the code

### CODE REVIEW

**Comment by Gutz-Pilz** [comment]
i manually changed the code in the addon...
works perfectly fine!

**Comment by emackey** [comment]
Looks like the "roughness" fix is also needed in gltf2_blender_gather_material_normal_texture_info_class.py.

**Comment by emackey** [comment]
Actually does the importer import tex transform on normal maps?

**Comment by julienduroure** [comment]
@emackey Added the code for normalmap texture

About importer, you're right, this is now solved in #658

**Pull request merged**
