### PR TITLE
fix(init): log level critical to info

### PR DESCRIPTION
**Pull request by clementlecorre**
Hi,
I think the critical level is not good.
I'm using a http://sentry.io/ integration with your lib, his errors are triggered.
Thanks

### CODE REVIEW

**Comment by scurest** [comment]
Fixes #613.

Since log.info messages don't show up by default, could we `print` here instead?

**Comment by julienduroure** [comment]
Agreed with scurest, log.info don't show up by default, so not the best choice.
My best choice would be to use Formatter to display critical without red color

**Comment by clementlecorre** [comment]
Ok, I replaced logging info with `print()`.

**Comment by julienduroure** [comment]
Maybe not the best logging solution, but merging it as is for now, waiting a better solution

**Pull request merged**
