### PR TITLE
Fix #1510 - use relative path when possible

### LINKED ISSUE #1510: Import: respect "Default To Relative Paths" preference
When the .blend file has been saved, and `context.preferences.filepaths.use_relative_paths` is on, the importer should load images using relative paths (`//foo.png`), instead of absolute.

[Some relevant OBJ code](https://github.com/sobotka/blender-addons/blob/c60fef38175ad989ee0c45e924cb27e1417c8667/io_scene_obj/__init__.py#L147-L149)
[An old issue for the same thing in OBJ](https://developer.blender.org/T34864)

### PR DESCRIPTION
**Pull request by julienduroure**
Fix #1510 - use relative path when possible

### CODE REVIEW

**Comment by julienduroure** [comment]
@scurest Can you please have a look?

**Comment by scurest** [comment]
Just one thing: on Windows, a relative path may not exist (eg. between `C:\file.blend` and `D:\image.png`). In that case, `bpy.path.relpath` raises a ValueError. So in the if-body I would do

```py
try:
    path = bpy.path.relpath(path)
except ValueError:
    # May happen on Windows if on different drives, eg. C:\ and D:\
    pass
```

This still uses the absolute path if no relative path exists, which is what happens if you load the image by hand.

**Comment by scurest** [comment]
Oh, you should really get rid of the outer `try` that swallows all exceptions too though. It existed to guard the tempdir with a finally. Since there's no tempdir it's not needed and swallowing all errors is bad.

**Comment by scurest** [comment]
The relpath code is messed up. There's no abspath and there's two relpaths now.

**Pull request merged**
