### PR TITLE
Export: roundtrip all texture wrap modes

### PR DESCRIPTION
**Pull request by scurest**
This teaches the exporter to recognize and roundtrip the node setup the importer uses for "unusual" wrap modes (see #926, #971).

Also add a roundtrip test that tests Mirror x Mirror and Repeat x Clamp modes

Tangentially, it also now exports Blender's CLIP extension mode (all pixels outside the edges are transparent) as ClampToEdge; this is not correct, but it seems better than Repeat. This suggestion came from #1113.

### CODE REVIEW

**Comment by scurest** [comment]
@emackey cf https://github.com/KhronosGroup/glTF-Blender-IO/issues/926#issuecomment-587813773

**Comment by scurest** [comment]
I've pushed commits to allow the KHR_texture_transform/texCoord code to skip over the wrapping nodes too. This means the exporter should now be able to roundtrip all the nodes the importer creates to hang off a texture node.

ex

**Comment by scurest** [comment]
Any progress? @emackey?

**Review by emackey — APPROVED** [review]
This looks great to me.  Thanks for including the full test!

**Comment by scurest** [comment]
@emackey So what's this waiting on then?

**Comment by emackey** [comment]
Was just leaving some room for @julienduroure or anyone else to comment or review, I figured they would take a bit more time during the holidays.

But I see you tagged a related issue, so I'll push this one along.  Thanks!

**Pull request merged**
