### PR TITLE
feat: finish importer extension

### PR DESCRIPTION
**Pull request by pepperoni505**
This PR finishes the importer user extension. It adds hooks detailed below, allows developers to register extensions required to the importer, and adds a custom panel to the import UI.

Added hooks:
- `gather_import_material_before_hook(self, gltf_material, vertex_color, import_settings)`
- `gather_import_material_after_hook(self, gltf_material, vertex_color, blender_mat, import_settings)`
- `gather_import_light_before_hook(self, gltf_node, gltf_light, import_settings)`
- `gather_import_light_after_hook(self, gltf_node, blender_node, blender_light, import_settings)`
- `gather_import_mesh_before_hook(self, gltf_mesh, import_settings)`
- `gather_import_mesh_after_hook(self, gltf_mesh, blender_mesh, import_settings)`
- `gather_import_camera_before_hook(self, gltf_node, gltf_camera, import_settings)`
- `gather_import_camera_after_hook(self, gltf_node, blender_node, blender_camera, import_settings)`
- `gather_import_image_before_hook(self, gltf_img, import_settings)`
- `gather_import_image_after_hook(self, gltf_img, blender_image, import_settings)`
- `gather_import_texture_before_hook(self, gltf_texture, mh, tex_info, location, label, color_socket, alpha_socket, is_data, import_settings)`
- `gather_import_texture_after_hook(self, gltf_texture, node_tree, mh, tex_info, location, label, color_socket, alpha_socket, is_data, import_settings)`
- `gather_import_animation_channel_before_hook(self, gltf_animation, gltf_node, path, channel, import_settings)`
- `gather_import_animation_channel_after_hook(self, gltf_animation, gltf_node, path, channel, blender_action, import_settings)`
- `gather_import_animation_weight_before_hook(self, gltf_node, blender_animation, import_settings)`
- `gather_import_animation_weight_after_hook(self, gltf_node, blender_animation, import_settings)`

Merging closes #1491

### CODE REVIEW

**Comment by pepperoni505** [comment]
@julienduroure Are these hooks good?

**Comment by pepperoni505** [comment]
I also added the ability to register custom extensions in `io/imp/gltf2_io_gltf.py` in the `self.extensions_managed` list.

**Comment by julienduroure** [comment]
Thanks!
I will have a look soon.
I will also try every hook one by one, to be sure everything is OK.

**Comment by pepperoni505** [comment]
> Thanks! I will have a look soon. I will also try every hook one by one, to be sure everything is OK.

Any update on your testing?

**Comment by julienduroure** [comment]
I didn't check every hook, but looks good to me for what I saw.
I will merge it soon

**Comment by julienduroure** [comment]
@pepperoni505 Thanks a lot for your help finishing it!

**Comment by pepperoni505** [comment]
> @pepperoni505 Thanks a lot for your help finishing it!

No problem! Thanks for merging

**Pull request merged**
