### PR TITLE
animation export settings toggle to force export all animation tracks without optimization

### PR DESCRIPTION
**Pull request by weckr**
https://github.com/KhronosGroup/glTF-Blender-IO/issues/1559
tested it with blender 3.0 where it works

### CODE REVIEW

**Review by julienduroure — CHANGES_REQUESTED** [review]
About vocabulary: I think we can't name it "track", as this is the name of another concept in Blender (NLA)

**Comment by weckr** [comment]
Yeah, I thought naming could be an issue, honestly no idea what to is appropriate here, 
Export without filesize optimization
Force export all keyframes
?

**Comment by julienduroure** [comment]
@weckr Do you plan to work on this PR?

* You have to validate the CLA
* Update the PR

I'd like to have it merge during the following week. If we don't plan to, don't worry, I will manage it

**Comment by weckr** [comment]
I can rename it to optimize animation size then. My email in git wasnt setup properly tho because i was just using it for personal stuff, so im not sure i can validate the license easily... should i open a PR from a new branch or something like that... Cant I just write here that I agree with the license ...

**Comment by julienduroure** [comment]
@weckr I can't accept and validate work without the CLA validation
Closing this ticket.
I will manage the change on my side, except if another PR is proposed (and CLA validated) until then

**Pull request closed without merging**
