### PR TITLE
Import: allow undo

### LINKED ISSUE #1163: Import: undo issues
**Undo Doesn't Work**
1. Create a new file
2. Import CesiumMan
3. Undo

Nothing happens.

-----

**Undo Crashes Blender**
1. Create a new file
2. Add a Cube
3. Import CesiumMan
4. Undo

Blender reliably crashes.

### PR DESCRIPTION
**Pull request by scurest**
Fixes #1163.

I just copied the same bl_options as the OBJ/FBX importer.

(I don't know what `PRESET` does. The docs just say "Display a preset button with the operators settings".)

### CODE REVIEW

**Comment by donmccurdy** [comment]
I guess PRESET is the menu at the top of the import settings? Could you confirm it works, e.g. that saving and selecting a preset switches the settings successfully in the import menu?

**Comment by donmccurdy** [comment]
**glTF:**
Screen Shot 2020-08-03 at 5 28 28 PM


**FBX:**
Screen Shot 2020-08-03 at 5 28 19 PM

**Comment by scurest** [comment]
Ohhhhhh. I've never looked at that before lol. It does work for me. Do you want to keep it?

**Comment by donmccurdy** [comment]
Sure, let's keep it. 👍

**Pull request merged**
