### PR TITLE
Fix #1509 images may be needlessly re-encoded in some cases

### LINKED ISSUE #1509: Export: images may be needlessly re-encoded in some cases
Look at this code for getting the already-encoded data for an image

https://github.com/KhronosGroup/glTF-Blender-IO/blob/3bc2858c714d5b517aa521a632906934fafdd4a8/addons/io_scene_gltf2/blender/exp/gltf2_blender_image.py#L192-L200

This assumes `image.file_format` describes the content of the file on disk/packed file. But that's wrong, `image.file_format` is only the format to use when saving, cf #986. The file_format check should be removed.

To avoid an unnecessary file read in the case of a file on disk, a check for the file extension could be added.

Re-encoding would be especially bad for JPEGs, since it would be lossy.

### PR DESCRIPTION
**Pull request by julienduroure**
Fix #1509

### CODE REVIEW

**Comment by julienduroure** [comment]
@scurest Can you please have a look?

**Comment by scurest** [comment]
Yeah, I guess it should never re-encode now. You didn't want to try using the filepath to avoid unnecessarily fetching image data?

**Comment by julienduroure** [comment]
> You didn't want to try using the filepath to avoid unnecessarily fetching image data?

Sorry, I am not sure to follow you, and a bit lost on what check/fetch exactly you want to avoid

**Comment by scurest** [comment]
The point of the file_format check was if the file isn't the right type, you can avoid reading the entire file just to find out it's the wrong type and you can't use it.

Ideally even an unneeded `packed_file.data` access would be avoided, since every time that's accessed the data is copied over into a new object on the Python side. But that's less bad than unneeded file IO.

**Pull request merged**
