### PR TITLE
feat: add import animation hooks

### PR DESCRIPTION
**Pull request by pepperoni505**
This adds two more hooks to the import animation cycle:
```
gather_import_animation_before_hook(self, gltf, anim_idx, import_settings)
gather_import_animation_after_hook(self, gltf, anim_idx, track_name, import_settings)
```

If these changes are ok, is it possible for it to be included in 3.1.X releases?

### CODE REVIEW

**Comment by julienduroure** [comment]
Hello,
Too late for 3.1
Code freeze was one week ago, and stable release should happen today

**Comment by pepperoni505** [comment]
Should the hooks be moved to `/blender/imp/gltf2_blender_animation.py` instead?

**Comment by julienduroure** [comment]
In blender_animation, it will make hooks for generic, as it will manage woth TRS animations and shapekeys animations

**Comment by pepperoni505** [comment]
So I should move it there?

**Comment by julienduroure** [comment]
yes please. More generic case will avoid to create a new one later for shapekeys animation

**Comment by pepperoni505** [comment]
Ok, it's moved. Can you check to make sure this is good?

**Comment by pepperoni505** [comment]
Merging into #1591

**Pull request closed without merging**
