### PR TITLE
feat: export node groups

### LINKED ISSUE #1141: NodeGroups in Materials are not traversed on export
**Describe the bug**
We have some cases where NodeGroups are reused between objects and where it would be great to directly export GLB files from. However, currently NodeGroups are not traversed (even if they contain just a single BSDF node); not sure if that counts as bug or feature request though.

**To Reproduce**
1. Create monkey
2. Create material
3. Export
3. Wrap BSDF node in NodeGroup (Ctrl + G)
4. Export

**Expected behavior**
Same result for both cases above, NodeGroup is "unrolled" on export to best-guess properties

**Actual behaviour**
Materials with NodeGroup always export as default white material

**Screenshots**
image

**.blend file/ .gltf**
[GLB-NodeGroup-Issues.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/4966295/GLB-NodeGroup-Issues.zip)

### PR DESCRIPTION
**Pull request by pepperoni505**
Fixes #1141

This PR adds the ability for the exporter to search inside custom shader node groups. This is very useful for those who chose to use custom node groups

### CODE REVIEW

**Comment by julienduroure** [comment]
@pepperoni505 Did you see you have a failing test?

**Comment by pepperoni505** [comment]
Yeah, I just noticed it. I'll fix it later today

**Comment by pepperoni505** [comment]
@julienduroure Fixed the unit test

**Comment by julienduroure** [comment]
@scurest : 
I know that you work a lot on material node tree traversal. Could be great if you can have a look on this PR.
Maybe there are some impacts that you have in mind.
Thanks!

**Comment by scurest** [comment]
I've never used get_socket, I always use previous_socket. Teaching that to search through groups would require passing state around (a stack so it could both enter and exit groups).

What cases does it handle? IIUC it will handle an entire piece of the graph being in a group

    GROUP(Texture->Principled->)->Output

but not where a link crosses a group boundary

    GROUP(Texture->)->Principled->Output
    Texture->GROUP(->Principled->)->Output

and not multiply nested groups

    GROUP(GROUP(Texture->Principled->)->)->Output

**Comment by pepperoni505** [comment]
Pushed a commit to search covering the crossing group boundary case. I can't figure out nested groups or how to properly implement `previous_socket`

**Comment by pepperoni505** [comment]
Another potential option of doing this, although probably not the best, would be to create a temporary material that "flattens" all the node groups, and then use that material to traverse sockets

**Comment by juanmarin96** [comment]
Do you planning add this feature in sometime?, what could be a workaround?

**Comment by pepperoni505** [comment]
> Do you planning add this feature in sometime?, what could be a workaround?

Looking back at this PR, the implementation is very limited and messy. I don't see myself working on it anytime soon, so someone else would need to go about implementing it

**Comment by julienduroure** [comment]
I have already a branch with some tests. Still WIP for now, not yet ready to be tested

**Comment by Claw256** [comment]
@julienduroure Hello, I had a look for the branch you mentioned you were doing some tests on, with the node groups feature implemented. Is the effort to implement this pull request into the main Khronos repo still ongoing? Here's the branch I was referring to I was trying out: https://github.com/KhronosGroup/glTF-Blender-IO/tree/node_tree_refactoring. I cloned that branch of the repo, and tried out the WIP feature, but I ran into an error when I tried exporting a skinned model with Shader node groups:
```python
04:10:44 | INFO: Extracting primitive: Torso_Mesh
04:10:44 | INFO: Primitives created: 3
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\__init__.py", line 689, in execute
    return gltf2_blender_export.save(context, export_settings)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_export.py", line 46, in save
    json, buffer = __export(export_settings)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_export.py", line 63, in __export
    __gather_gltf(exporter, export_settings)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_export.py", line 77, in __gather_gltf
    active_scene_idx, scenes, animations = gltf2_blender_gather.gather_gltf2(export_settings)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather.py", line 41, in gather_gltf2
    scenes.append(__gather_scene(blender_scene, export_settings))
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_cache.py", line 49, in wrapper_cached
    result = func(*args, **kwargs)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather.py", line 80, in __gather_scene
    node = gltf2_blender_gather_nodes.gather_node(
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_nodes.py", line 45, in gather_node
    children=__gather_children(vnode, blender_object, export_settings),
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_nodes.py", line 84, in __gather_children
    node = gather_node(c, export_settings)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_nodes.py", line 49, in gather_node
    mesh=__gather_mesh(vnode, blender_object, export_settings),
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_nodes.py", line 257, in __gather_mesh
    result = gltf2_blender_gather_mesh.gather_mesh(blender_mesh,
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_cache.py", line 49, in wrapper_cached
    result = func(*args, **kwargs)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_mesh.py", line 72, in gather_mesh
    primitives=__gather_primitives(blender_mesh, uuid_for_skined_data, vertex_groups, modifiers, materials, export_settings),
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_mesh.py", line 158, in __gather_primitives
    return gltf2_blender_gather_primitives.gather_primitives(blender_mesh,
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_cache.py", line 49, in wrapper_cached
    result = func(*args, **kwargs)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_primitives.py", line 94, in gather_primitives
    material = gltf2_blender_gather_materials.gather_material(
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_cache.py", line 49, in wrapper_cached
    result = func(*args, **kwargs)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_materials.py", line 72, in gather_material
    extensions, uvmap_actives_extensions = __gather_extensions(blender_material, emissive_factor, export_settings)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_materials.py", line 244, in __gather_extensions
    specular_extension, use_actives_uvmap_specular = export_specular(blender_material, export_settings)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_materials_specular.py", line 107, in export_specular
    base_color_not_linked = not has_image_node_from_socket(base_color_socket, export_settings)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_search_node_tree.py", line 142, in has_image_node_from_socket
    result = get_texture_node_from_socket(socket, export_settings)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_cache.py", line 49, in wrapper_cached
    result = func(*args, **kwargs)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_search_node_tree.py", line 132, in get_texture_node_from_socket
    result = from_socket(
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_search_node_tree.py", line 128, in from_socket
    return __search_from_socket(start_socket.socket, shader_node_filter, [], start_socket.group_path)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_search_node_tree.py", line 117, in __search_from_socket
    linked_results = __search_from_socket(input_socket, shader_node_filter, search_path + [link], group_path)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_search_node_tree.py", line 117, in __search_from_socket
    linked_results = __search_from_socket(input_socket, shader_node_filter, search_path + [link], group_path)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_search_node_tree.py", line 117, in __search_from_socket
    linked_results = __search_from_socket(input_socket, shader_node_filter, search_path + [link], group_path)
  [Previous line repeated 1 more time]
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_search_node_tree.py", line 96, in __search_from_socket
    linked_results = __search_from_socket(socket, shader_node_filter, search_path + [link], group_path)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_search_node_tree.py", line 117, in __search_from_socket
    linked_results = __search_from_socket(input_socket, shader_node_filter, search_path + [link], group_path)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_search_node_tree.py", line 117, in __search_from_socket
    linked_results = __search_from_socket(input_socket, shader_node_filter, search_path + [link], group_path)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_search_node_tree.py", line 117, in __search_from_socket
    linked_results = __search_from_socket(input_socket, shader_node_filter, search_path + [link], group_path)
  [Previous line repeated 1 more time]
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_search_node_tree.py", line 104, in __search_from_socket
    socket = [sock for sock in group_path[-1].inputs if sock.name == link.from_socket.name][0]
IndexError: list index out of range
```
Any idea of what I could do to solve this?

**Comment by julienduroure** [comment]
@Claw256 Can you share the .blend file your are trying to export?

There is currently no estimated time for this to be merge into master, but yes, this PR is still in TODO list, and this feature will definitively be part of official release one day.

Thanks !

**Comment by julienduroure** [comment]
Closing this PR, as a more robust solution is now in main branch

**Comment by Claw256** [comment]
> Closing this PR, as a more robust solution is now in main branch

Hi @julienduroure, great to hear about this implementation. Can you link to the specific commits or pull request where this solution was implemented into the main branch?

**Comment by julienduroure** [comment]
Here is the PR: https://github.com/KhronosGroup/glTF-Blender-IO/pull/1735/files

**Comment by Claw256** [comment]
> Here is the PR: [#1735 (files)](https://github.com/KhronosGroup/glTF-Blender-IO/pull/1735/files)

Thanks for this. with this PR now merged is the glTF addon able export procedural materials with nested node groups outside of Blender, or would I have to look for other solutiosn elsewhere such as OpenUSD with MaterialX for exporting my object from Blender into a game engine? I've attached my Blender 3.6.5 `.blend` file that I want to export the nested node trees from if you could have a look.

\- Fearghal

[Bell_Seperate.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/13297723/Bell_Seperate.zip)

**Pull request closed without merging**
