### PR TITLE
Import: rewrite mesh importer with numpy

### PR DESCRIPTION
**Pull request by scurest**
Rewrites the mesh import code to use numpy and foreach_set, as discussed in #996.

The first commit adds accessor decoding to numpy arrays. The existing functions are kept for compat with existing callers.

The second rewrites gltf2_blender_mesh.py. Code is pretty straightforward, just ask if there's anything you want to know about.

This is usually either good for performance, or neutral. Sometimes it is slower, but seems worth it on the balance.

|Model|master|this branch|
|:---|:---|:---|
|modelGroup.glb, Smooth Shading|110s|47s|
|MetalRoughSpheres|5.1|3.4s|
|AliciaSolid (iss967)|1.5s|0.5s|
|RubyRose (iss848)|2.1s|**2.4s**|

This code structure also makes it pretty easy to dedupe verts for #1069; PR to follow.

### CODE REVIEW

**Comment by scurest** [comment]
I realized I re-implemented the import shading handling wrong (in master, custom split normals is only set when "Use Normal Data" is on; here, I set it whenever we have normals). Let's block this until #1119 is resolved.

**Comment by julienduroure** [comment]
I converted this PR to draft until the normal issue is solved

**Comment by scurest** [comment]
Nvm lol, I just went ahead and fixed it 'cause it was easy. For some reason I always thought the big difference between "Use Normal Data" and "Flat Shading"/"Smooth Shading" was how it set the poly's use_smooths, but it was actually that "Use Normal Data" creates custom normals and the others don't.

Since "Smooth Shading" now doesn't create split normals it's also even faster! modelGroup.glb is now a cool 35s :o

**Comment by scurest** [comment]
I pushed some more optimizations and RubyRose is no longer slower than master.

**Comment by julienduroure** [comment]
Thanks!

**Comment by julienduroure** [comment]
@Scurest 

Some comment from Blender developer team:

> Hi @Julien DUROURE (julien) it is advised to put imports inside function body to avoid inflating Blender startup time.
Many imports load very fast and have little impact, but numpy takes 0.14 seconds to load on my machine, and that is a significant portion of Blender's 2 second startup time.

**Pull request merged**
