### PR TITLE
Use LINEAR interpolation when sampling anims

### PR DESCRIPTION
**Pull request by pjoe**
Not sure why this ever used STEP :)

With LINEAR you can get decent result with sampling every few frames (e.g. 3-4 depending on your animation), instead of the chunky result you will get with STEP

### CODE REVIEW

**Comment by pjoe** [comment]
Sample file, with sampling every 4 frames:

[anim_sampling.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/3063001/anim_sampling.zip)

Tried capturing the difference in gifs

STEP:
step

LINEAR:
linear

**Comment by pjoe** [comment]
@UX3D-becher OK, I understand the issue, but for end user this really should be handled automatically. I'll try to see how difficult it is to handle the case with only 1 keyframe.

Having to manually bake anims is a complication of the workflow, and also to some extend makes the export process less 'non-destructive'.

**Comment by pjoe** [comment]
@UX3D-becher something like this should do it 92c50f7d32f34ebf891c9bb90d4a566e2b010a54

**Comment by emackey** [comment]
@UX3D-becher I find that reasoning a little odd.  Wouldn't it be better to file bug reports against engines that can't handle an individual linear keyframe?

I guess having a workaround here doesn't hurt much, but thus far the pattern has been to insist on filing issues and fixing problems rather than bending the format spec to accommodate bugs.

**Comment by emackey** [comment]
Fixes #369

**Comment by donmccurdy** [comment]
Agreed that LINEAR interpolation should be used for baking whenever possible. Engines are not rendering at 24-30 fps, which the keyframes usually are. Whether single-keyframe tracks should use STEP or LINEAR I'm not sure.

**Comment by donmccurdy** [comment]
Hm, but this will go to STEP for all channels, if any channel has a single keyframe? I might prefer LINEAR in that case...

**Comment by emackey** [comment]
Ouch.  Would definitely prefer LINEAR in that case.

**Comment by pjoe** [comment]
I am all for always using LINEAR and would consider it a weird edge case / bug if engines don't handle it correctly. So I can easily revert last commit if we agree on this? Or try to add further detection of single channel (won't there always be 3 or 4 together?) Anyway this PR improves behavior in most common cases (more then 1 key), so can also be merged as is and we can further tackle the single key/STEP issue in separate PR

**Comment by pjoe** [comment]
After thinking/testing this some more:

I believe the best option is to use LINEAR if any of the channels in a sampler has more than 1 keyframe,
since loc/scale/rot will get each their sampler and glTF will batch together each subcomponent, i.e. glTF doesn't support having different interpolation (or number of keys) for e.g. loc.x and loc.y anyway.

If anyone can come up with a case where this would break - speak up 😄 

Otherwise I think it is good to go now

**Comment by emackey** [comment]
Any objections @UX3D-becher @donmccurdy ?

**Comment by donmccurdy** [comment]
Sounds good to me. I could imagine CUBICSPLINE causing problems with a single keyframe, but STEP and LINEAR seem completely reasonable. If there's a bug in e.g. threejs we can certainly fix those.

**Pull request merged**
