### PR TITLE
Export: support use_nodes=False materials

### LINKED ISSUE #571: Diffuse BSDF and use_nodes=False are not supported.
**Describe the bug**

Materials colors are not exported

Taking this file

[Cow.blend.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/3334088/Cow.blend.zip)

Exporting with the old exporter I get this

Screen Shot 2019-06-27 at 18 46 27

With the current export (cloned from the repo) I get this

Screen Shot 2019-06-27 at 18 46 52

**To Reproduce**
1. Download the attached file, unzip, double click the .blend file
2. File->Export->glTF 2.0
3. Export
4. Load in a viewer

**Expected behavior**

There are material colors

Checking the gltf data the old exporter has this

```
    "materials" : [
        {
            "name" : "Black",
            "pbrMetallicRoughness" : {
                "baseColorFactor" : [
                    0.02327823673603291,
                    0.02327823673603291,
                    0.02327823673603291,
                    1.0
                ],
                "metallicFactor" : 0.0
            }
        },
        {
            "name" : "Pink",
            "pbrMetallicRoughness" : {
                "baseColorFactor" : [
                    0.640000066757203,
                    0.1408390542989828,
                    0.1733517791830268,
                    1.0
                ],
                "metallicFactor" : 0.0
            }
        },
        {
            "name" : "White",
            "pbrMetallicRoughness" : {
                "baseColorFactor" : [
                    0.6400000190734865,
                    0.6400000190734865,
                    0.6400000190734865,
                    1.0
                ],
                "metallicFactor" : 0.0
            }
        }
    ],
```

the new exporter only this

```
    "materials" : [
        {
            "name" : "White",
            "pbrMetallicRoughness" : {}
        },
        {
            "name" : "Black",
            "pbrMetallicRoughness" : {}
        },
        {
            "name" : "Pink",
            "pbrMetallicRoughness" : {}
        }
    ],
```

yes, export materials was checked

**Version**
 - OS: macOS
 - Blender Version 2.79

### PR DESCRIPTION
**Pull request by scurest**
Fixes #571. Cow.blend exports as expected.

### CODE REVIEW

**Comment by julienduroure** [comment]
Can you please rebase please @scurest ?

**Comment by scurest** [comment]
Yeah, rebased.

**Comment by scurest** [comment]
@julienduroure Respond please.

**Comment by julienduroure** [comment]
Thanks!

**Pull request merged**
