### PR TITLE
Export: more fixes for changing the filename when format changed (#718)

### PR DESCRIPTION
**Pull request by scurest**
Further fixes to the `on_export_format_changed` junk.

* When exporting using the Python console in master, it will fail if passing `export_format=` because `context.space_data.active_operator` is None, and `on_export_format_changed` does not handle that. Further defensive checks have been added to prevent this. (I've also checked that #1281 did not regress.)
* The hack with `bpy.ops.file.filenum` was replaced with setting `context.space_data.params.filename`, which is much cleaner. This is thanks to batFINGER's [answer](https://blender.stackexchange.com/a/207665/88681) to my question on Blender SE.

### CODE REVIEW

**Comment by scurest** [comment]
@donmccurdy @julienduroure @emackey

**Review by donmccurdy — APPROVED** [review]
Looks good to me, thank you! I'll merge this in ~2 days if there are no objections (and if no one merges it before I do).

**Review by emackey — APPROVED** [review]
Thanks so much @scurest for your continued patience with us.

**Comment by scurest** [comment]
Since this is a bugfix, will it be backported to the 2.92 branch?

**Comment by julienduroure** [comment]
I will backport and merge with blender repo tonight

**Comment by julienduroure** [comment]
Done!

**Pull request merged**
