### PR TITLE
accessibility through search bar

### PR DESCRIPTION
**Pull request by Vinc3r**
not such a big thing but could make search easier (plus it acts like other export file formats)

img

### CODE REVIEW

**Comment by donmccurdy** [comment]
Does this not affect the File -> Export menu too? 🤔

**Comment by Vinc3r** [comment]
Since I don't modified line 435 (and also after tested of course), it should not.

```PYTHON
def menu_func_export(self, context):
   self.layout.operator(ExportGLTF2.bl_idname, text='glTF 2.0 (.glb/.gltf)')
```

**Comment by donmccurdy** [comment]
Thanks!

**Comment by donmccurdy** [comment]
Good catch! Also tweaked this to remove the extensions, better matching the rest of the list:

screen shot 2019-02-08 at 12 53 40 pm

**Pull request merged**
