### PR TITLE
Fix #2090

### LINKED ISSUE #2090: 'NoneType' object has no attribute 'joints'
I already saw this issue in #1738 issue and you seemed to say that it was fixed, but it appears again in version 4

`Traceback (most recent call last):
  File "D:\blender4\4.0\python\lib\bpy\4.0\scripts\addons\io_scene_gltf2\__init__.py", line 1125, in execute
    return gltf2_blender_export.save(context, export_settings)
  File "D:\blender4\4.0\python\lib\bpy\4.0\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_export.py", line 49, in save
    json, buffer = __export(export_settings)
  File "D:\blender4\4.0\python\lib\bpy\4.0\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_export.py", line 66, in __export
    __gather_gltf(exporter, export_settings)
  File "D:\blender4\4.0\python\lib\bpy\4.0\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_export.py", line 95, in __gather_gltf
    active_scene_idx, scenes, animations = gltf2_blender_gather.gather_gltf2(export_settings)
  File "D:\blender4\4.0\python\lib\bpy\4.0\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather.py", line 40, in gather_gltf2
    scenes.append(__gather_scene(blender_scene, export_settings))
  File "D:\blender4\4.0\python\lib\bpy\4.0\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_cache.py", line 46, in wrapper_cached
    result = func(*args, **kwargs)
  File "D:\blender4\4.0\python\lib\bpy\4.0\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather.py", line 123, in __gather_scene
    vtree.add_neutral_bones()
  File "D:\blender4\4.0\python\lib\bpy\4.0\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_tree.py", line 613, in add_neutral_bones
    n.node.skin.joints.append(neutral_bone)
AttributeError: 'NoneType' object has no attribute 'joints'
2023-12-19 11:07:02,619 - ERROR - [runConvert:1719] - Error: Python: Traceback (most recent call last):
  File "D:\blender4\4.0\python\lib\bpy\4.0\scripts\addons\io_scene_gltf2\__init__.py", line 1125, in execute
    return gltf2_blender_export.save(context, export_settings)
  File "D:\blender4\4.0\python\lib\bpy\4.0\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_export.py", line 49, in save
    json, buffer = __export(export_settings)
  File "D:\blender4\4.0\python\lib\bpy\4.0\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_export.py", line 66, in __export
    __gather_gltf(exporter, export_settings)
  File "D:\blender4\4.0\python\lib\bpy\4.0\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_export.py", line 95, in __gather_gltf
    active_scene_idx, scenes, animations = gltf2_blender_gather.gather_gltf2(export_settings)
  File "D:\blender4\4.0\python\lib\bpy\4.0\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather.py", line 40, in gather_gltf2
    scenes.append(__gather_scene(blender_scene, export_settings))
  File "D:\blender4\4.0\python\lib\bpy\4.0\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_cache.py", line 46, in wrapper_cached
    result = func(*args, **kwargs)
  File "D:\blender4\4.0\python\lib\bpy\4.0\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather.py", line 123, in __gather_scene
    vtree.add_neutral_bones()
  File "D:\blender4\4.0\python\lib\bpy\4.0\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_tree.py", line 613, in add_neutral_bones
    n.node.skin.joints.append(neutral_bone)
AttributeError: 'NoneType' object has no attribute 'joints'
Location: D:\blender4\4.0\python\lib\bpy\4.0\scripts\modules\bpy\ops.py:109
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\python\python.py", line 1696, in runConvert
    bpy.ops.export_scene.gltf(
  File "D:\blender4\4.0\python\lib\bpy\4.0\scripts\modules\bpy\ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "D:\blender4\4.0\python\lib\bpy\4.0\scripts\addons\io_scene_gltf2\__init__.py", line 1125, in execute
    return gltf2_blender_export.save(context, export_settings)
  File "D:\blender4\4.0\python\lib\bpy\4.0\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_export.py", line 49, in save
    json, buffer = __export(export_settings)
  File "D:\blender4\4.0\python\lib\bpy\4.0\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_export.py", line 66, in __export
    __gather_gltf(exporter, export_settings)
  File "D:\blender4\4.0\python\lib\bpy\4.0\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_export.py", line 95, in __gather_gltf
    active_scene_idx, scenes, animations = gltf2_blender_gather.gather_gltf2(export_settings)
  File "D:\blender4\4.0\python\lib\bpy\4.0\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather.py", line 40, in gather_gltf2
    scenes.append(__gather_scene(blender_scene, export_settings))
  File "D:\blender4\4.0\python\lib\bpy\4.0\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_cache.py", line 46, in wrapper_cached
    result = func(*args, **kwargs)
  File "D:\blender4\4.0\python\lib\bpy\4.0\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather.py", line 123, in __gather_scene
    vtree.add_neutral_bones()
  File "D:\blender4\4.0\python\lib\bpy\4.0\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_tree.py", line 613, in add_neutral_bones
    n.node.skin.joints.append(neutral_bone)
AttributeError: 'NoneType' object has no attribute 'joints'
Location: D:\blender4\4.0\python\lib\bpy\4.0\scripts\modules\bpy\ops.py:109`

### PR DESCRIPTION
**Pull request by julienduroure**
Fix #2090 Add a check to avoid crash when there is a mesh without any data in it

### CODE REVIEW

**Comment by julienduroure** [comment]
Regression is on Blender side
See https://projects.blender.org/blender/blender/issues/116373

**Comment by Balzx** [comment]
Can you stop spamming on my Gmail? I feel annoyed by your message.

Pada Rab, 20 Des 2023 17.57, Julien Duroure ***@***.***>
menulis:

**Comment by Balzx** [comment]
how to delete this repository?

Pada Rab, 20 Des 2023 18.02, Julien Duroure ***@***.***>
menulis:

**Comment by julienduroure** [comment]
You can't "delete" the repository.
You have to go on https://github.com/KhronosGroup/glTF-Blender-IO
And then click on "Unwatch"
image

**Pull request merged**
