### PR TITLE
Extended information string in case no binary provided

### PR DESCRIPTION
**Pull request by flakusha**
In case binary file is not included in Blender3D installation it would be nice for user to know the fastest way to solve the problem without visiting source files.

My case is that Blender3D uses OS Python libraries and adding ```blender_root / python_lib / python_version / 'site_packages'``` folder to my installation breaks Python or some of it's dependencies. Adding BLENDER_EXTERN_DRACO_LIBRARY_PATH with binary file is the fastest way to solve a problem.

### CODE REVIEW

**Comment by julienduroure** [comment]
@Ralith Can you please rebase with master? I fixed an issue with CI checks

**Comment by julienduroure** [comment]
@flakusha Can you please rebase with master? I fixed an issue with CI checks

**Comment by flakusha** [comment]
Hello! Sure, I will do this, busy at the moment :(

**Comment by flakusha** [comment]
@julienduroure is everything all right? Can this pull request be closed, or I should change my fork and retry?

**Pull request merged**
