### PR TITLE
Scurest mesh creation dev

### PR DESCRIPTION
**Pull request by julienduroure**

### CODE REVIEW

**Comment by julienduroure** [comment]
Oups, didn't push it in already existing PR ... Closing this one

**Comment by scurest** [comment]
@julienduroure 
Saw this, caching accessors is very nice! What do you think about adding an optional `cache` parameter to `BinaryData.get_data_from_accessor` instead? So it'd look like eg.

````python
BinaryData.get_data_from_accessor(gltf, attributes['POSITION'], cache=True)
````

Would be shorter and easier to reuse I think (might be useful for caching the input accessor for samplers later on too, those often get used multiple times).

**Comment by julienduroure** [comment]
Yes, this can be a great code refactoring enhancement. I already pushed the fix to master, (because I need it right now for my job), but fill free to propose a PR if you want to do it. (or create a ticket if you want me to remember)

**Comment by scurest** [comment]
Ok, thanks :)

**Pull request closed without merging**
