### PR TITLE
Import: improve the layout of nodes in the material graph

### PR DESCRIPTION
**Pull request by scurest**
Done on top of #1061, merge that first.

Followup to https://github.com/KhronosGroup/glTF-Blender-IO/pull/1061#issuecomment-626096178. The pieces of the node graph (emission, base color, etc.) were placed at fixed positions before this. This makes a simple pass over the material before we start creating stuff to choose a position for each piece.

The pieces are now (more or less) centered vertically on the Principled node.

Here's an example before/after for a material with only a normal and clearcoatNormal texture

out

I rearranged the blocks so they go in the same order as the sockets on the Principled node. For example, emission (whose socket was at the very top in 2.79) is now near the bottom.

The node with the occlusion hookup is also placed just underneath the Principled node now.

### CODE REVIEW

**Comment by scurest** [comment]
Another example. Material has an emissive, normal, and occlusion texture.

out

**Comment by julienduroure** [comment]
@scurest Can you please rebase? It will be easier for me to review with only diff from this PR

**Comment by scurest** [comment]
Yeah, no problem.

**Comment by scurest** [comment]
@julienduroure Any update?

**Comment by julienduroure** [comment]
Hello,
I approve the changes. I will merge it soon.

Sorry, not so much time to work on it these days.
Lockdown is not an easy time : Much work, less time. Hope my calendar will go back to normal in following weeks

**Pull request merged**
