### PR TITLE
Import: set scene's frame_{start,end} when restoring animation

### PR DESCRIPTION
**Pull request by scurest**
Minor enhancement for animations. When restoring an animation, set the scene's start/end frame so it will loop at the proper places when you play it in the Timeline.

out

### CODE REVIEW

**Comment by julienduroure** [comment]
What about if a file has multiple animation with different lengths? Currently, it will set start/end, based on restored animation, but if other animation is more long, it will be "truncated" by default, until the user change start/end by hand.

Note sure what we have to do here:
* keeping as in master?
* Based on restored animation?
* Based on longer animation?

**Comment by scurest** [comment]
Right, to "play" an animation, you have to change the start/end by hand, just like you have to set all the actions by hand. You already have to set the start/end for every animation including the default one. This PR would do it for you for the default one.

No matter what the start/end can only be set correctly for one animation at a time. The others will all either be extended or truncated. So from my point of view the choice is either we set it, in which case we can make it correct for exactly one animation, or we don't, in which case we make it correct for zero animations.

**Comment by scurest** [comment]
If you don't want to change it, it could also just be an enhancement idea for the theoretical feature that will play an NLA strip for you (#840). The script I'm using for that sets the start/end for you.

**Comment by julienduroure** [comment]
I am absolutely not saying I don't want to change it.
I only starting a discussion with all of you to be sure that we are choosing to better solution.
Sorry if you thought it was a remark against your solution. It is definitely not.

**Comment by scurest** [comment]
Ahh, I didn't think that, but feel free to remark against it if you want to lol :) I was also weighing the value of having the animation loop right vs. preserving the existing values of the start/end.

**Comment by scurest** [comment]
Well, since the story of how animations should work hasn't been totally nailed down yet, I'll close this as premature for now. It can get revisited when everyone agrees what the design should be.

**Pull request closed without merging**
