### PR TITLE
Add tests for texture transform roundtrip/export

### PR DESCRIPTION
**Pull request by emackey**
/cc @pjoe

### CODE REVIEW

**Comment by pjoe** [comment]
A bit confused about the js dependency handling here. Aren't we using `yarn`? Then there should be updates to `yarn.lock`

**Comment by emackey** [comment]
Oh, yeah.  Thanks for catching that, I was just installing things with npm locally.  I'll have to get yarn installed for this.

**Comment by pjoe** [comment]
Been debating npm vs. yarn a number of times in the past ... always ended up settling on yarn, mileage my vary of course :)

**Comment by emackey** [comment]
Any particular version of yarn I should install?  Website shows 1.15.2 as the default currently.  Also I guess we should update the README to mention it.

**Comment by pjoe** [comment]
Latest yarn should be fine

**Comment by emackey** [comment]
Updated.

**Comment by pjoe** [comment]
@emackey 👍

**Pull request merged**
