### PR TITLE
Implementation of punctual lights

### PR DESCRIPTION
**Pull request by julienduroure**

### CODE REVIEW

**Comment by UX3D-nopper** [comment]
Have you cross checked, if your solution also works, when the light is animated?
Actually, the same problem occurs with the camera.

**Comment by julienduroure** [comment]
@UX3D-nopper I added support for light animation (tested with light animation exported from blender, and imported back)

I checked for camera, but it seems to work (tested with camera animation exported from blender, and imported back)

**Comment by julienduroure** [comment]
@UX3D-schmithuesen If possible, I would like to manage myself PR merging / stuff regarding importer part of the addon

**Comment by UX3D-schmithuesen** [comment]
Okay, sure! So you just want some comments when you create a PR?

**Pull request merged**
