### PR TITLE
Fix export of vertex groups in skinned model

### PR DESCRIPTION
**Pull request by Peach1**
Export failed when vertex_group_index was out of range

### CODE REVIEW

**Comment by julienduroure** [comment]
I supposed this is a fix for #909 ?
Even for PR, please always include some test cases, or link to ticket that will be solve: it will help me a lot!

Note that a more general subject about that is #900, but this PR can be a good first step

**Comment by Peach1** [comment]
I can confirm that it fixes the same error in #909 
Same Error As 909
I can send a blend test case if needed

**Comment by Peach1** [comment]
Here is a test case, the error occurred when one armature has multiple meshes attached  [export_test_pr963.blend.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/4303946/export_test_pr963.blend.zip)

Before the patch, it would not export
After the patch, it exports as expected

GLTF playback tested via: https://gltf-viewer.donmccurdy.com/

**Comment by julienduroure** [comment]
Your analysis is not right, this is not linked to having multiple meshes attached on the same armature. Cf a simplified version of your file in attachement, with only 1 mesh and 1 bone --> still crash.
I prefer not to commit this fix, until we found the real root cause.


[export_vertex_group.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/4305276/export_vertex_group.zip)

**Comment by Peach1** [comment]
Thanks for the test case. 
The root issue is when vertex groups reference data that is no longer in the scene.

In the test case, there are vertex groups that refer to deleted geometry
Extra Vertex Groups

This leads to vertex_group_index going out of range and causes the crash `IndexError: bpy_prop_collection[index]: index 44 out of range, size 11`

The patch fixes the crash by filtering out the vertex group indexes that reference data not in range of the current scene.

**Pull request merged**
