### PR TITLE
Fix #993 Draco UV export

### LINKED ISSUE #916: Exporting object with correct UV map defined in Shader Editor [DRACO]
**Describe the bug**
Exporter is creating GLTF object with first UV map from the list "UV maps" ignoring "UV map" node in material in Shader Editor WHEN draco compression is turned on

**To Reproduce**
Compare applied texture on exported objects with and without draco compression 

**Expected behavior**
Result should look like without draco compression

**Screenshots**
image

**.blend file/ .gltf**
blend file with 2 gltf samples (correct and wrong result)
[github-issue.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/4170623/github-issue.zip)

**Version**
- OS: [Windows10 Home]
- Blender Version [2.80 (sub 75), branch: master, commit date: 2019-07-29 14:47, hash: f6cb5f54494e, type: build date: 2019-07-29, 09:44 AM platform: Windows]

**Additional context**

### LINKED ISSUE #917: Exporting 2 cubes with UV maps + draco compression => WebGL Error
Hi,

it took me more than a day of trying to narrow this weird problem down. Attached is a sample file with two cubes and a texture applied:
image

If I export this scene to GLTF / GLB and open it up with https://gltf-viewer.donmccurdy.com/, it shows the following errors:
image

Visually, everything seems OK. However, I have a large model which gives the same error message and misses 90% of the objects when I load it in ThreeJS. I assume that these issues are connected.

The error is somehow related to the UV maps and DRACO compression. If I remove the UV map on one of the cubes, it solves the issue. If I disable DRACO compression, it also solves it.

[gltf bug report.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/4239566/gltf.bug.report.zip)
**Update 2020-02-22: Fixed missing texture in blend file**

I would greatly appreciate any help with this issue.

**Version**
 - OS: Manjaro Linux
 - Blender Version: 2.83 / 2.82

### LINKED ISSUE #988: T74924: Draco export error
See https://developer.blender.org/T74924

### LINKED ISSUE #993: Misaligned UV coordinates after Draco compression
**Describe the bug:**
All mesh UVs are misaligned after the very first mesh in the scene while using Draco compression

**Steps to reproduce the behavior:**
Compare two objects with and without Draco comprasion.

**Expected behavior:**
UVs must be aligned properly for each mesh in the scene.

**Video description of the issue:**
https://www.youtube.com/embed/UAbaHDGpXJY

**.blend file/ .gltf**
[Misaligned UV coordinates after Draco compression.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/4380713/Misaligned.UV.coordinates.after.Draco.compression.zip)

**Version**
 - OS: [Windows 10 Pro]
 - Blender Version [2.82a]

**Additional context: Temporary solution**
The issue is caused by the TEXCOORD_0 attribute if you change the value of it to the value of the first mesh TEXCOORD_0 value. The issue will be fixed. (You can do it for all meshes in the scene).

see the image:
image

similar issues:
1. Exporting 2 cubes with UV maps + Draco compression => WebGL Error #917 
2. Exporting object with correct UV map defined in Shader Editor [DRACO] #916

### LINKED ISSUE #1006: T75132: draco compression not including multiple materials
See https://developer.blender.org/T75132

### LINKED ISSUE #1079: Draco UV Issue
Hi,
We've previously operated a `3dsMax -> glTF` workflow but changed to `Blender` recently. The Draco compression that came with the `Babylon exporter for 3dsMax` produced a working and optimized result, however the `in-built glTF exporter for Blender` is not working for us when we check the "`Draco mesh compression`" box in the glTF export UI. We can't open the model due to various errors.

We're therefor very curious about what Draco version that's being used with Blender 2.8 so that we can add support for it with our app.

### PR DESCRIPTION
**Pull request by julienduroure**
Fix #993 
Fix #1079
Fix #1006
Fix #988
Fix #917
Fix #916

### CODE REVIEW

**Comment by scurest** [comment]
Nice, six issues with three characters :)  
You probably meant #988 instead of #998.

**Comment by julienduroure** [comment]
Yes, you're right. I edited
Too much numbers for me ;-)

**Comment by SBRK** [comment]
@julienduroure do you know when this will be included to Blender ? This was merged almost a month ago, yet the new Blender release from 6 days ago (2.83.2) still has the problem. It's the only thing preventing us from switching to 2.83

**Comment by julienduroure** [comment]
@SBRK This is merged in 2.90 alpha/beta version, not in 2.83.x

**Pull request merged**
