### PR TITLE
Export: don't mess with normals when doing Apply Modifiers

### LINKED ISSUE #877: Normals / Modifier refactoring
- [ ] How to detect if a modifier changes some normals ? See #860 and #874 
- [ ] See #799 
- [ ] #100 Custom normals in SK bug
- [ ] See #911

### LINKED ISSUE #975: Custom normals are lost when exporting w Apply Modifiers checked
I'm losing custom normals when exporting using Apply Modifiers:
Blender 2.82 (Win 10 64-bit), web viewer https://gltf-viewer.donmccurdy.com/
[Bug.custom.normals.discarded.by.gltf.export.if.apply.modifiers.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/4333677/Bug.custom.normals.discarded.by.gltf.export.if.apply.modifiers.zip)
75896958-1a430200-5e38-11ea-8a1c-78ae011ba685

### PR DESCRIPTION
**Pull request by scurest**
Fixes #877.  
Fixes #975.

Deletes the code that applies a temp edge split modifier and messes with use_auto_smooth when "Apply Modifiers" is used. As far as I could tell these are no longer needed. The OBJ/FBX exporter also don't appear to do anything like this. If anyone has a model that this code was supposed to fix it would be great to test it.

### CODE REVIEW

**Comment by scurest** [comment]
It's been over a month for this too, and now I need it for another PR.

It makes it impossible to get anything done when no one will respond to anything in a reasonable time frame. It shouldn't take weeks and months for every single thing. It's by far the biggest problem with the repo.

**Comment by julienduroure** [comment]
Sorry to ear that :-/
I'm not here to talk about my private life, but I'm here on my free time. Already have a wife, 3 children, a full time job and some freelancing job. I know that I'm probably  the bottleneck here, but this is the open-source project life: Days are only 24 hours.

Back to original issue:
I know this modifier/normals issue waits long time I finished to test it. I know this is a non trivial task with many different regression test cases to perform, to be sure everything is correct. Probably why I postponed it to much. Will work on it on my next free time slot

**Comment by donmccurdy** [comment]
On the PR — I don't know of any reason this code was needed. In the future we should probably try to include unit tests (or at least comments in code) explaining why seemingly-unnecessary code exists. Since it appears to be causing issues without fixing anything, I'm OK with merging this if others don't have any concerns. Generally speaking, a PR should not be blocked for the possibility that unknown test models might exist, we should add these cases to tests. Would it be possible to include a test for the issue in #877 and #975? If that's difficult to test for some reason, I can take a look at it.

***

On the process — Honestly, issues and PRs from any given repository get buried pretty quickly in my notifications. On a PR like this, where (most likely) no one knows the answer to your question, that makes it very easy to assume someone else has the answer, and then forget about it. 

In terms of improving the situation, I'm *very* grateful for your contributions to the project, but I can't realistically promise I'll never miss an important PR, and I wouldn't want to ask @emackey or @julienduroure to promise that either. What we can (perhaps) do would be to set expectations for code review times, and steps to take when those expectations aren't met. For example:

1. Aim to provide an initial review (rotating reviewers?) on PRs within ~1 week.
2. If a reviewer is not available, maintainers can merge PRs unilaterally after this time.
3. Provide more visibility into which PRs to prioritize; please feel free to comment, label issues, or assign reviewers accordingly.

@scurest to ask your help with 1–3 above, you're more than welcome to have Collaborator status on this repository. Your additions to this project are valuable, and I don't want to waste your time on blocked PRs because of my own limited time/attention. Even if you'd rather not merge PRs without a code review (which obviously should be our goal) Collaborator status would allow you to request a review more directly and re-label issues for priority.

**Comment by scurest** [comment]
I added an export test for #975, `10_custom_normals_with_modifier`. It's a quad with rotated normals and an Array modifier. It fails on master but passes on this branch.

apptest

There wasn't a way to use the "Apply Modifiers" options from a test, so I also changed the export script to pass any settings stored for "Remember Export Settings". That let's the test suite test non-default options now. If you have a different idea for how to pass export options along, just tell me.

As a bonus, that means the test should also exercise "Apply Modifiers" for this first time, so the tests will catch if it stops working like in #546.

The reason CI failed is this branch is still on 2.90. I can rebase if you would like.

**Comment by scurest** [comment]
It's not like I like whining about this either. And I'm not asking anyone to be bound to some 1 week deadline or anything like that.

But it's not like people aren't _around_. Issues _do_ get responded to quick, and if there's something wrong in a PR that usually gets a quick response too. It's specifically when it comes to actually merging code that no one seems to want to do it. I don't know if this is, like, fear of regressions (do the tests need to be beefed up?), or if it's a pain to sync with upstream in Blender, or something else. It doesn't even seem to make a difference if the change is small or large or safe or dangerous either.

And like, the emission strength PR did get approved, 11 days ago. But it's not merged. Why is that? That happens all the time.

**Comment by julienduroure** [comment]
On process: 
I already answer to this, I don't have to justify me on schedule/agenda. Merging need my own PC, where answer can be done on my Pro PC. Things are done, maybe with delay, but are done. Please be patient.

On this PR: yes, fear of regression. Modifers & vertexGroups are missed cached, that why there was lots of stuff (bad stuff) before to detect if we need that.

**Comment by julienduroure** [comment]
@scurest yes please, can you please rebase, to avoid test errors?

**Comment by julienduroure** [comment]
Code was added for #599 , so we need to test regression on file from #599 too

**Comment by scurest** [comment]
Rebased. CI segfaulted in Blender for some reason, I'll amend a few times and see if it clears up.

I tested the file from #599 and there was no difference from master.

**Comment by scurest** [comment]
All export tests (including on master and on blender-v2.83-release) are failing on the current nightly Blender build on Linux, namely `blender-2.91.0-6624c4c22514-linux64`, which is why the CI doesn't work.

In other news, if you amend a branch to be identical to master, the PR for that branch is automatically closed.

**Comment by emackey** [comment]
I don't think I can write anything here that would be more eloquent than what Don wrote above.  This summer has been a challenge, but I'm hopeful the fall will be an improvement.

I've seen other large open-source projects drift in this direction as well, where the maintainers have families and day jobs that keep them busy elsewhere.  Open PRs with thorny questions or unknown implications will sit around open, as would-be reviewers are unsure of themselves and realize they can quickly get more productive by looking at something else.  In one case, a bot was introduced, to bump stale open PRs for every 30 days of inactivity.  I'm not sure if this helped or just made the silence that much more embarrassing.  Sometimes it directly helps, for example if notifications were dismissed by a reviewer who thought a different reviewer would be a better person to merge.  But it doesn't help if there are lingering concerns on a given PR.

But back to this repo.  The nightly build breakage has bad timing here given this conversation, so I hope that gets resolved in tomorrow's build.  Generally my thoughts on tests are, we should lean on them even more:  Every feature we care about should be covered by tests, so if a developer wants to remove some old lines of code, and the tests don't break, we can confidently say we don't need those old lines of code.  Conversely, any new feature added should have tests to go along with it, else the once-new feature can and will be removed by someone wondering why those lines of code are there.  I know our tests aren't up at that strength level yet, but getting there might alleviate a lot of lingering concerns about whether it was safe to remove certain lines of code.  And I have noticed a couple of PRs recently include new tests, so that's going in the right direction.

So for this PR, once the tests are green again, let's merge this, deleting the old code and adding a new test.  If it breaks something that anyone cares about, we'll write another test for that.  I'll try to contribute some more tests as well, time permitting.

**Comment by julienduroure** [comment]
I started to list all different cases we can encounter, and create corresponding .blend file
I will share it as soon as it is ready.
Plan is still to include it to 2.91

**Comment by scurest** [comment]
I guess I can also do a test like in https://github.com/KhronosGroup/glTF-Blender-IO/issues/1119#issuecomment-659597910. Again, how this works: create a Suzanne, mess with her normals, export (with Apply Modifiers), reimport, and take a screenshot to compare. Do this in a loop, varying "mess with her normals", then put all the screenshots together to compare.

<details>

<summary>Expand to see images</summary>

Using master, Apply Modifier, No modifiers

ma

Using this branch, Apply Modifiers, No modifiers

ma

Using master, Apply Modifiers, Subsurf modifier (levels=1, use_custom_normals=True)

ma

Using this branch, Apply Modifiers, Subsurf modifier (levels=1, use_custom_normals=True)

ma

</details>

The only case where they obviously differ is precisely #975, (smooth faces + autosmooth + custom normals).

They also differ in the case (smooth faces + autosmooth + no custom normals), but it's so small it's imperceptible.

([Here](https://gist.github.com/scurest/05e3f8a8b98ae52dfad9b1766943f29c) is the script I used.)

**Comment by scurest** [comment]
Update?

**Comment by julienduroure** [comment]
I almost finished my tests - everything is ok for now.
Just want to test some rigged models with custom normals.
Will merge before end of week

**Comment by julienduroure** [comment]
Let's merge this !
Thanks !

Seems this is the last merge of multiple PR concerning new way of exporting normals.
Seems this is much more stable and solid now.
Thanks again @scurest

**Pull request merged**
