### PR TITLE
Take care of active output material node

### LINKED ISSUE #1213: T78926: Materials export blank if unconnected Principled BSDF node is anywhere in a "Background" material
See https://developer.blender.org/T78926

Is same problem that in #1114

Maybe we can check if output is linked (directly or not) to Material Output node?

### LINKED ISSUE #1248: Ability to detect "is_active_output"on OUTPUT_MATERIAL node
It could be useful to have multiple Material Outputs on our materials. One node tree for Cycles, another for glTF, another one for texture baking, etc.

I've notice that the glTF exporter doesn't care about the `is_active_output` and/or `mute` property of an OUTPUT_MATERIAL node, and just take the first in the material nodes list.

A nice feature would be to take into account only node tree linked to the current active output.

Screenshot below, from the .blend in attachment, give you an example. My active output use an UVGrid texture, my inactive output use a ColorGrid texture. The exported node tree is the one which is inactive.

image

[material-output.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/5422567/material-output.zip)

### PR DESCRIPTION
**Pull request by julienduroure**
Fix #1248 Fix #1213
Take care of active output material node

Material node tree can have multiple output node.
Only 1 can be active.

This PR:
* Check that nodes are linked to any output material node
* and that node is the active one

Not sure how this will work with background rendering, when there is no user to click on an output node to activate it

### CODE REVIEW

**Comment by julienduroure** [comment]
Ok, think this is ready for review :)

**Comment by Vinc3r** [comment]
Works fine on my tiny test scene in #1248 ✌

**Comment by cstfan** [comment]
I have just tested on my current project, also works for me. Thanks to @julienduroure for the quick correction.

**Comment by cstfan** [comment]
Very great news

**Pull request merged**
